### PR TITLE
cmake: set CMAKE_CXX_STANDARD 17 to match code assumptions

### PR DESCRIPTION
**Pull request by erkki**
Usage of std::in_place_t implies C++17

Build on macOS 15.3.2 fails otherwise with:

```
/opt/homebrew/Cellar/abseil/20250127.1/include/absl/utility/utility.h:85:12: fatal error: no member named 'in_place_t' in namespace 'std'
   85 | using std::in_place_t;
      |       ~~~~~^
1 error generated.

```

### CODE REVIEW

**Comment by dagar** [comment]
This should be fine, but let's take a closer look at a Nuttx build for any differences and get it through CI cleanly.

**Comment by farhangnaderi** [comment]
@dagar could you give a hint here how to keep this going?

**Comment by erkki** [comment]
I was actually wanting to understand this more (which is why the draft mode), seems abseil should be able to run in compat mode too, not requiring C17. To not force a project decision due to a (minor) dependency.

Not sure if there's any project discussion on adopting C17 in general but not to cross streams.

**Comment by farhangnaderi** [comment]
> I was actually wanting to understand this more (which is why the draft mode), seems abseil should be able to run in compat mode too, not requiring C17. To not force a project decision due to a (minor) dependency.
> 
> Not sure if there's any project discussion on adopting C17 in general but not to cross streams.

Yup yup, cause now am trying to fix macOS build issues and this PR popped up and I have same issue locally.

**Comment by PetervdPerk-NXP** [comment]
> > I was actually wanting to understand this more (which is why the draft mode), seems abseil should be able to run in compat mode too, not requiring C17. To not force a project decision due to a (minor) dependency.
> > Not sure if there's any project discussion on adopting C17 in general but not to cross streams.
> 
> Yup yup, cause now am trying to fix macOS build issues and this PR popped up and I have same issue locally.

Which target are you guys trying to build, it's quite ambiguous here?

Like how come absl we're pulling the absl lib?

**Comment by farhangnaderi** [comment]
@PetervdPerk-NXP 
current target am trying is `px4_sitl gz_x500`

**Comment by farhangnaderi** [comment]
@PetervdPerk-NXP @dagar @mrpollo :

Homebrew installs the latest version of abseil-cpp but they already have ended c++14 support. Protobuf seems to be built against latest abseil as well which requires c++17 . That is why if we want to run gz on macOS hands are tight I guess with CXX14:
https://github.com/abseil/abseil-cpp/releases/tag/20250127.0

cc: #25204

**Comment by hamishwillee** [comment]
@mrpollo @dakejahl Can we merge this? 

This one of the dependencies required to have a macOS toolchain for Gazebo without lots of "caveats" for users - #25979

As I understand it, we're currently telling CMAKE that the compiler can use features in C++14, and we have a dependency on a component that can't be built without C++17 on macOS (abseil, a dependency of protobuf).

Ubuntu probably shouldn't be working as it also has this dependency. We're just getting lucky because for some reason it is less strict that macOS.

In any case, both Ubuntu 22.04 and Ubuntu 24.04 work with this change (tested using `make px4_sitl gz_x500`) and unless we need to support an older platform with this tookchain, it would be OK to upgrade.

**Comment by hamishwillee** [comment]
@dakejahl Copilot gave you its amazing review :-(

**Review by dakejahl — APPROVED** [review]
