### ISSUE TITLE
mavlink_types.h not found

### ISSUE THREAD

**Issue by unphased** [PX4/PX4-Autopilot#1219]
Not sure if I'm doing something wrong. I am just trying to compile again (on OSX here) after leaving the project sit for about a month and a half. 

I'm seeing 

```
CXX:     /Users/me/Documents/px4/Firmware/src/modules/mavlink/mavlink_main.cpp
In file included from /Users/me/Documents/px4/Firmware/src/modules/mavlink/mavlink_main.cpp:76:0:
/Users/me/Documents/px4/Firmware/src/modules/mavlink/mavlink_bridge_header.h:55:32: fatal error: v1.0/mavlink_types.h: No such file or directory
compilation terminated.
make[2]: *** [mavlink_main.cpp.o] Error 1
```

No mavlink_types.h exists in entire repo.

**Comment by ViKrAm-Bais** [comment]
> git submodule init
> git submodule update



> Hi,
> 
> It looks a bit like a bad merge. We changed mavlink from binary to a git submodule (files remained the same, just the way how they are pulled changed), so after merging you would have to do:
> 
> ```
> git submodule init
> git submodule update
> ```
> 
> There are no fundamental changes that otherwise should break at the locations where it broke for you. Closing this issue as its not a problem with the codebase - please ping us on the mailing list for questions.

at which location we have to run this command ??
