### PR TITLE
Pr resillience2

### PR DESCRIPTION
**Pull request by Louis-max-H**
### Solved Problem

When errors occur in attached GNSS receivers, there is no way to report them to the user so they know what is going wrong.

This is an update of PR made by @flyingthingsintothings 
https://github.com/PX4/PX4-Autopilot/pull/23096

### Solution
- Add automatic configuration for Septentrio receivers to report resilience information every second
- Add to Septentrio parser so it can parse the new message 
- Change the uORB message for GNSS information to support this new 
- MAVLink message is in development.xml, you need to pass `CONFIG_MAVLINK_DIALECT="development"` to your `default.px4board`

Changelog Entry

For release notes:
```
Feature: Report resilience information from GNSS receivers
Documentation: Need to clarify page ...
```

### Test coverage
- I have tested this PR using a Septentrio receiver to emulate jamming, there was just a typo that has now been fixed.

### Context
- Link to old PR : https://github.com/PX4/PX4-Autopilot/pull/23096
- Link to QGC PR : To update

### CODE REVIEW

File: src/drivers/gnss/septentrio/CMakeLists.txt [hunk 1]
```diff
@@ -37,7 +37,7 @@ px4_add_module(
 	COMPILE_FLAGS
 		# -DDEBUG_BUILD           # Enable during development of the module
 		-DSEP_LOG_ERROR         # Enable module-level error logs
-		# -DSEP_LOG_WARN          # Enable module-level warning logs
+		-DSEP_LOG_WARN          # Enable module-level warning logs
```
Comment (mrpollo) [inline src/drivers/gnss/septentrio/CMakeLists.txt:40]: did you intend to keep this enabled?

File: src/drivers/ins/vectornav/VectorNav.cpp [hunk 2]
```diff
@@ -451,6 +451,13 @@ void VectorNav::sensorCallback(VnUartPacket *packet)
 			sensor_gps.hdop = dop.hDOP;
 			sensor_gps.vdop = dop.vDOP;
 
+			sensor_gps.heading = NAN;
```
Comment (mrpollo) [inline src/drivers/ins/vectornav/VectorNav.cpp]: Why do we need to add these params here?

File: src/drivers/gnss/septentrio/CMakeLists.txt (hunk 1 above)
Comment (Louis-max-H) [reply src/drivers/gnss/septentrio/CMakeLists.txt:40]: SEP_WARN really helped me a lot.
It gives you extra information when you fail to configure a receiver, and only adds very little print once the connection is successful.

But if the PX4 style code means that you have to keep the warnings commented out, I can restore the original version, it's as you want,

File: src/drivers/ins/vectornav/VectorNav.cpp (hunk 2 above)
Comment (Louis-max-H) [reply src/drivers/ins/vectornav/VectorNav.cpp]: The heading option is set to 0 if no value is available and NAN if heading is not configured.
For resillience variables, this specifies that we do not yet have any information,

Alternatively, I can move the default value directly into the definition of sensor_gps_s. I'll do that tomorrow (it's 10pm in Brussels).
That will be cleaner, thanks for the review !

File: src/drivers/gnss/septentrio/CMakeLists.txt (hunk 1 above)
Comment (Louis-max-H) [reply src/drivers/gnss/septentrio/CMakeLists.txt:40]: I have checked in ubx.cpp, warn is also activate by default.

As a result, I mark this has resolved, but feel free to deactivate warning if you prefer so,

**Review by Louis-max-H — COMMENTED** [review]
I have tested this version with Septentrio receiver and Jamming/Spoofing emulation.

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+	{
+		sensor_gps_s gps;
+		mavlink_gnss_integrity_t msg{};
+		hrt_abstime now{};
+
+		if (_sensor_gps_sub.update(&gps)) {
+			msg.id = gps.device_id;
+
+			if (gps.system_error & sensor_gps_s::SYSTEM_ERROR_ANTENNA) {
+				msg.system_errors |= 8;
```
Comment (dagar) [inline src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]:
```suggestion
				msg.system_errors |= GPS_SYSTEM_ERROR_ANTENNA;
```

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+			}
+
+			if (gps.system_error & sensor_gps_s::SYSTEM_ERROR_SOFTWARE) {
+				msg.system_errors |= 4;
```
Comment (dagar) [inline src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]: use the constants from mavlink https://mavlink.io/en/messages/development.html#GPS_SYSTEM_ERROR_FLAGS

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp (hunk 3 above)
Comment (Louis-max-H) [reply src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]: GNSS_INTEGRITY.hpp have been simplified after this review, thanks !

**Comment by Louis-max-H** [comment]
Hi :wave: 
Here is a quick update of this PR before the dev call, 

- Mavlink message have now 0 for default value (encoding 0 to 10 value to 1 to 11) has discussed in Mavlink discord channel. PR link : https://github.com/mavlink/mavlink/pull/2293

- I have renamed spoofing and jamming to match mavlink message :
    JAMMING_STATE_WARNING    -> JAMMING_STATE_MITIGATED
    JAMMING_STATE_CRITICAL   -> JAMMING_STATE_DETECTED
    SPOOFING_STATE_NONE      -> SPOOFING_STATE_OK
    SPOOFING_STATE_INDICATED -> SPOOFING_STATE_MITIGATED
    SPOOFING_STATE_MULTIPLE  -> SPOOFING_STATE_DETECTED
    
- GNSS_INTEGRITY.hpp have been simplified, no more constant needed
- I have tested my change with a Septentrio receiver

I need more time to check raim (default value is not 0 in mavlink message)
I will test on Ublox before re-opening this PR.

**Comment by mrpollo** [comment]
@hamishwillee can you check wha'ts wrong with the docs ci?

**Comment by hamishwillee** [comment]
> @hamishwillee can you check wha'ts wrong with the docs ci?

Yes, it's an error in a translation file that should have been removed. I'm fixing this in #25120

**Review by dakejahl — COMMENTED** [review]
Wouldn't it make more sense to create a new separate uORB message for this data? As far as I know this data is specific to Septentrio GPSs. If we used a separate publisher we wouldn't have the issue with zero initialization for these added fields, and this wouldn't impact any of the other GPS code. The GNSS_INTEGRITY mavlink stream could then subscribe to this new message, such that the mavlink message is only emitted when a septentrio receiver is connected and publishing.

**Comment by Louis-max-H** [comment]
I have updated this PR to :
- Add uORB `gps_status` that include all 4 quality metrics
- Update `GNSS_INTEGRITY.hpp` to :
    - Send one message when at least, `sensor_gps` or `gps_status` is updated
    - Set value to 0 for `gps_sensor` and 255 for `gps_status` when we have no data for a long time
- Send gps status information in Septentrio receiver

I have tested on QGroundControl, values are correctly set for Septentrio receiver.
image


Feel free to ask me some changes if needed, I may have time to do it before the dev call :)

Ps: I am not passing SITL test, should I change something ?

File: msg/CMakeLists.txt [hunk 5]
```diff
@@ -111,6 +111,7 @@ set(msg_files
 	GpioRequest.msg
 	GpsDump.msg
 	GpsInjectData.msg
+	GpsStatus.msg
```
Comment (dagar) [inline msg/CMakeLists.txt]: We're slowly moving the naming from GPS -> GNSS, so for anything new we might as well start there.

```suggestion
	SensorGnssStatus.msg
```

Additionally please include a device_id field so we know which receiver is providing this information.

https://github.com/PX4/PX4-Autopilot/blob/ae9a21f0c4c44d6d2123120c6ba37b55294dea47/msg/SensorGps.msg#L2-L6

Comment (Louis-max-H) [reply msg/CMakeLists.txt]: Thanks ! I have updated the code,

**Comment by farhangnaderi** [comment]
@dagar you might wanna take a look, please! Thanks.

**Review by Louis-max-H — COMMENTED** [review]
I have just review and tested this PR @dagar  :smiley: 

The merge conflict was caused by https://github.com/Louis-max-H/PX4-Autopilot/commit/6ee6a3a5788ab39a252f962231f65457e257c352, I have kept theirs changes and restore _jamming_state in Septentrio driver.

Tory9 will be taking over this PR, and we've discussed and tested it and the one for QGroundControl together.
I'll continue to follow the changes, but I'll have limited access to the hardware with the end of my internship,

File: docs/en/msg_docs/SensorGps.md [hunk 6]
```diff
@@ -38,18 +38,19 @@ float32 vdop			# Vertical dilution of precision
 int32 noise_per_ms		# GPS noise per millisecond
```
Comment (hamishwillee) [inline docs/en/msg_docs/SensorGps.md]: Please remove the changes under /docs 

1. The updates will come automatically from the uorb messages themselves.
2. Generally if you DID have to change these, you would only update the files under `/docs/en` - the rest are translations such as  `/docs/zh/`, and they are updated automatically by round tripping through  a translation service.

**Comment by mrpollo** [comment]
@Louis-max-H, [CI seems to have caught an issue](https://github.com/PX4/PX4-Autopilot/actions/runs/16339548557/job/46158644814?pr=25012#step:8:4190). Can you please look into this?

```
  ../../src/drivers/gnss/septentrio/septentrio.cpp: In member function ‘septentrio::SeptentrioDriver::ConfigureResult septentrio::SeptentrioDriver::configure()’:
  ../../src/drivers/gnss/septentrio/septentrio.cpp:970:36: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘uint32_t’ {aka ‘unsigned int’} [-Werror=format=]
    970 |         snprintf(msg, sizeof(msg), k_command_sbf_output_pvt, _receiver_stream_main, com_port, sbf_frequency);
        |                                    ^~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~
        |                                                              |
        |                                                              uint32_t {aka unsigned int}
  compilation terminated due to -Wfatal-errors.
  cc1plus: all warnings being treated as errors
```

**Comment by Tory9** [comment]
Hi @hamishwillee, @mrpollo , i will fix these over the weekend and let you know that its done

**Comment by Tory9** [comment]
@mrpollo I've fixed the error, and the docs should now be in sync. please let me know if there's anything else I need to change, or if it's ready for final review

**Comment by mrpollo** [comment]
Can you please look into the failing tests? Let us know if you need help with the errors.

**Comment by Tory9** [comment]
Hi @mrpollo. I've resolved the failing tests related to my code changes. The only remaining failure is on the macOS build, which shows a SHA256 mismatch error which appears to be a CI environment issue that is out of my control (correct me pls if i am wrong)

**Comment by Tory9** [comment]
Hello @mrpollo, could you pls let me know if there is anything you need me to address before the dev call tomorrow? We're hoping to get this ready for final review.

**Comment by hamishwillee** [comment]
When this goes in and has been verified, it is important to move https://mavlink.io/en/messages/development.html#GNSS_INTEGRITY to common.xml and explain what testing has been done to verify this _before_ it goes into a release.

Also some docs would be nice, though presumably that can be in QGC.

**Comment by Tory9** [comment]
Thanks for the reply! I'll bring this up on the dev call to clarify the specific expectations for the testing report and docs. To ensure we can get this done in time, what's the deadline for these changes to be considered for the next release?

**Comment by hamishwillee** [comment]
> Thanks for the reply! I'll bring this up on the dev call to clarify the specific expectations for the testing report and docs. To ensure we can get this done in time, what's the deadline for these changes to be considered for the next release?

Assuming you mean the PX4 dev call and release, they will know about the deadline. Right now I think the way this is handled is after this merges you create a backport PR into the release/1.16 and any additional requirements go there.

My interest here is in MAVLink. Things in development that go into release builds are a real pain because stakeholders don't have to take them - then we end up with common.xml being forked ... more.
The testing we need is a bit up the air. Confirming what fields are actually used and are useful would be a good start - i.e. not just set to the invalid values. Any information you have showing that they allow successful real world debugging, and so on. 
We're after due diligence. Remember that changing this later is very hard.

**Comment by Tory9** [comment]
Hi @dagar! During last week's dev call, you mentioned this pr needed an extra review. I just wanted to check in and see if there’s any feedback or changes I can address in preparation for the call tomorrow?

**Comment by Tory9** [comment]
Hi @dagar, you asked for some clarification on the status mapping during the last dev call. I've attached a file with some explanations. I also sent you a dm on Discord in case that's easier.
[resiliencePR.pdf](https://github.com/user-attachments/files/21849937/resiliencePR.pdf)

File: src/examples/fake_gps/FakeGps.cpp [hunk 7]
```diff
@@ -87,6 +87,13 @@ void FakeGps::Run()
 	sensor_gps.satellites_used = 14;
 	sensor_gps.timestamp = hrt_absolute_time();
 	_sensor_gps_pub.publish(sensor_gps);
+
+	sensor_gnss_status_s sensor_gnss_status{};
+	sensor_gnss_status.quality_corrections = 0;
+	sensor_gnss_status.quality_receiver = 9;
+	sensor_gnss_status.quality_gnss_signals = 10;
+	sensor_gnss_status.quality_post_processing = 255;
+	_sensor_gnss_status_pub.publish(sensor_gnss_status);
```
Comment (dagar) [inline src/examples/fake_gps/FakeGps.cpp:97]: At a minimum you need to populate the timestamp and device id fields.

Comment (dagar) [inline src/examples/fake_gps/FakeGps.cpp:97]:
```suggestion
	sensor_gnss_status.timestamp = hrt_absolute_time();
	_sensor_gnss_status_pub.publish(sensor_gnss_status);
```

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp [hunk 8]
```diff
@@ -0,0 +1,130 @@
...
+private:
+	explicit MavlinkStreamGNSSIntegrity(Mavlink *mavlink) : MavlinkStream(mavlink) {}
+
+	uORB::Subscription _sensor_gps_sub{ORB_ID(sensor_gps), 0};
+	uORB::Subscription _sensor_gnss_status_sub{ORB_ID(sensor_gnss_status), 0};
+
+	hrt_abstime _last_send_ts {};
+	hrt_abstime _last_gps_update_ts {};
+	hrt_abstime _last_status_update_ts {};
+	static constexpr hrt_abstime kNoGpsSendInterval {1_s};
```
Comment (dagar) [inline src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]:
```suggestion
```

Please drop all of this custom send interval, the mavlink module is in control of the rate per stream.

https://github.com/PX4/PX4-Autopilot/blob/b95da27f6b1baf23a65af32087fc839aa1e8aa6f/src/modules/mavlink/mavlink_main.cpp#L1438

The only thing send() should be checking is if there's new data (_sensor_gnss_status_sub.updated()).

File: msg/SensorGps.msg [hunk 9]
```diff
@@ -30,18 +30,26 @@ float32 vdop			# Vertical dilution of precision
...
+uint8 SPOOFING_STATE_DETECTED  = 3
+uint8 spoofing_state	       # indicates whether spoofing has been detected or suspected by the receivers. O: Unknown, 1: OK, 2: Mitigated, 3: Detected
+
+# Combined authentication state (e.g. Galileo OSNMA)
+uint8 AUTHENTICATION_STATE_UNKNOWN      = 0 #default
+uint8 AUTHENTICATION_STATE_INITIALIZING = 1
+uint8 AUTHENTICATION_STATE_ERROR        = 2
+uint8 AUTHENTICATION_STATE_OK           = 3
+uint8 AUTHENTICATION_STATE_DISABLED     = 4
+uint8 authentication_state              # GPS signal authentication state
```
Comment (dagar) [inline msg/SensorGps.msg:52]: I'm not exactly sure where the line is between sensor_gps and sensor_gnss_status, but as a start can you place all of these "status" fields into sensor_gnss_status as well?

File: msg/SensorGps.msg [hunk 10]
```diff
@@ -55,6 +63,16 @@ uint64 time_utc_usec		# Timestamp (microseconds, UTC), this is the timestamp whi
...
 
+uint32 SYSTEM_ERROR_OK                   = 0 #default
+uint32 SYSTEM_ERROR_INCOMING_CORRECTIONS = 1
+uint32 SYSTEM_ERROR_CONFIGURATION        = 2
+uint32 SYSTEM_ERROR_SOFTWARE             = 4
+uint32 SYSTEM_ERROR_ANTENNA              = 8
+uint32 SYSTEM_ERROR_EVENT_CONGESTION     = 16
+uint32 SYSTEM_ERROR_CPU_OVERLOAD         = 32
+uint32 SYSTEM_ERROR_OUTPUT_CONGESTION    = 64
+uint32 system_error                      # General errors with the connected GPS receiver
```
Comment (dagar) [inline msg/SensorGps.msg:74]: Seems like a good one for gnss status as well.

File: msg/SensorGnssStatus.msg [hunk 11]
```diff
@@ -0,0 +1,10 @@
+# Gnss quality indicators
+
+uint64 timestamp		# time since system start (microseconds)
+uint32 device_id                # unique device ID for the sensor that does not change between power cycles
+
+bool  quality_available         # Set to true if quality indicators are available
+uint8 quality_corrections       # Corrections quality from 0 to 10, or 255 if not available
```
Comment (dagar) [inline msg/SensorGnssStatus.msg:7]: Are all of these fields simply 0-10 with no specific meaning?

Unless the integer values are actually meaning can we publish them as a percentage in a float? That will be a bit more self explanatory from a log review standpoint.

File: msg/SensorGnssStatus.msg [hunk 12]
```diff
@@ -0,0 +1,10 @@
+# Gnss quality indicators
+
+uint64 timestamp		# time since system start (microseconds)
+uint32 device_id                # unique device ID for the sensor that does not change between power cycles
```
Comment (dagar) [inline msg/SensorGnssStatus.msg:4]: Make sure you populate the device_id everywhere, that's how we'll know with GNSS a particular sensor_gnss_status topic corresponds with (if there's more than 1).

File: src/drivers/gnss/septentrio/septentrio.cpp [hunk 13]
```diff
@@ -1191,20 +1191,134 @@ int SeptentrioDriver::process_message()
...
+
 			SEP_TRACE_PARSING("Processing QualityInd SBF message");
+
+			QualityInd quality_ind;
+
+			if (_sbf_decoder.parse(&quality_ind) == PX4_OK) {
+				_message_sensor_gnss_status.quality_available = true;
+				_message_sensor_gnss_status.device_id = get_device_id();
+
+				_message_sensor_gnss_status.quality_corrections = 255;
```
Comment (dagar) [inline src/drivers/gnss/septentrio/septentrio.cpp:1233]: We should avoid having to manually populate the field with 255 (UINT8_MAX) if not available. Think about all the other GNSS publishers that will need to manually populate these fields going forward. It needs to be structured so that future field additions won't require every single publisher updating, they should be able to opt in to using the new fields, but otherwise get away with zeroing the struct (sensor_gnss_status{}).

File: msg/SensorGnssStatus.msg (hunk 12 above)
Comment (Tory9) [reply msg/SensorGnssStatus.msg:4]: The device_id for the sensor_gnss_status message is populated within the process_message() function, specifically in the case BlockID::QualityInd: block.
This is the only location where the _message_sensor_gnss_status struct is populated, and the device_id is set immediately ( line1231 ) before the message is published. So it should be fine

File: msg/SensorGnssStatus.msg (hunk 11 above)
Comment (Tory9) [reply msg/SensorGnssStatus.msg:7]: The value represents a quality score where 0 indicates poor quality and 10 indicates excellent quality. We use an integer score instead of a percentage because a percentage could be misleading, implying something is "incomplete", this is aalso a common practice in other applications/daily life to rate smth not in percentages but based on the scale. Also such scoring keeps it consistent with the Septentrio [web tool](https://customersupport.septentrio.com/s/article/What-do-the-different-quality-indicators-in-the-web-interface-mean#:~:text=web%20interface%20mean?-,What%20do%20the%20different%20quality%20indicators%20in%20the%20web%20interface,quality%20indicators%20are%20explained%20below:), which is familiar to most users of this receiver. But we can further discuss this

File: src/drivers/gnss/septentrio/septentrio.cpp (hunk 13 above)
Comment (Tory9) [reply src/drivers/gnss/septentrio/septentrio.cpp:1233]: I agree that using UINT8_MAX for an "invalid" state is not ideal, and that zero-initializing the struct would be far more convenient for other publishers.
However, the challenge here is that for Septentrio receivers, as well as within the custom MAVLink message [GNSS_INTEGRITY (441)](https://mavlink.io/en/messages/development.html), the value 0 is a valid state. As a result, the convention to use UINT8_MAX for an invalid value was adopted in both the Septentrio Binary Format (SBF) and MAVLink implementations to avoid conflict.
This is a known concern that has been raised by other developers in thi pr before. As mentioned in the comments on this pull request,   Louis-max-H opened a MAVLink PR to change the valid states to a 1-11 range, which would have freed up 0 to be used for "invalid." That PR was closed after the MAVLink side stated it would be inconsistent and problematic. So at that point it was decided to keep it this way

File: src/examples/fake_gps/FakeGps.cpp (hunk 7 above)
Comment (Tory9) [reply src/examples/fake_gps/FakeGps.cpp:97]: Thanks for pointing this out

File: msg/SensorGps.msg (hunk 9 above)
Comment (Tory9) [reply msg/SensorGps.msg:52]: The separation of the topics was based on the original SBF messages and a logical split between critical and non-critical data.

The principle is to keep sensor_gps for essential, high-frequency parameters like position, system errors, and resilience data. In contrast, sensor_gnss_status is intended for more general, informative data that is less critical and does not require such frequent updates.

This design keeps the primary sensor_gps topic cleaner. It also makes sensor_gnss_status a flexible place to add more informational parameters in the future without overloading the main topic

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp (hunk 8 above)
Comment (Tory9) [reply src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]: Thanks for pointing this out. Let me clarify: the integrity data will be sent at its configured 1Hz rate. The kNoGpsSendInterval is only used to check if the resilience data is recent. If not, the message is still sent, but instead of using the stale data, its fields will indicate an "unknown" or "invalid" state as defined in MAVLink

**Comment by Tory9** [comment]
hi @dagar, I just wanted to check in and see if there’s any feedback or changes I can address in preparation for the call today?

**Comment by Tory9** [comment]
Hi @dagar! I just wanted to check in and see if there’s any feedback or changes I can address in preparation for the call tomorrow?

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+	sensor_gnss_status_s _status{};
+
+	bool send() override
+	{
+		// Check for new data and update local copies
+		const bool gps_updated = _sensor_gps_sub.update(&_gps);
+		const bool status_updated = _sensor_gnss_status_sub.update(&_status);
+
+		// Send only if there's new data for either topic
+		if (gps_updated || status_updated) {
```
Comment (dagar) [inline src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]: I would do this only when sensor_gps is updated and then within it grab the latest copy of sensor_gnss_status, but only use it if relatively new (< 1s old) and the device id matches.

```suggestion
		sensor_gps_s sensor_gps{};
		if (_sensor_gps_sub.update(&sensor_gps)) {
			mavlink_gnss_integrity_t msg{};
			
			msg.corrections_quality = UINT8_MAX;
			msg.system_status_summary = UINT8_MAX;
			msg.gnss_signal_quality = UINT8_MAX;
			msg.post_processing_quality = UINT8_MAX;
			
			sensor_gnss_status_s sensor_gnss_status{};
			if (_sensor_gnss_status_sub.copy(&sensor_gnss_status)) {
				if ((hrt_elapsed_time(&sensor_gnss_status.timestamp) < 1_s)
				&& (sensor_gnss_status.device_id == sensor_gps.device_id)
				&& (sensor_gnss_status.quality_available)
				) {
					msg.corrections_quality = sensor_gnss_status.quality_corrections;
					msg.system_status_summary = sensor_gnss_status.quality_receiver;
					msg.gnss_signal_quality = sensor_gnss_status.quality_gnss_signals;
					msg.post_processing_quality = sensor_gnss_status.quality_post_processing;
				}
```

File: src/modules/mavlink/streams/GNSS_INTEGRITY.hpp [hunk 15]
```diff
@@ -0,0 +1,111 @@
...
+
+	unsigned get_size() override
+	{
+		return _sensor_gps_sub.advertised() ? (MAVLINK_MSG_ID_GNSS_INTEGRITY_LEN + MAVLINK_NUM_NON_PAYLOAD_BYTES) : 0;
+	}
+
+private:
+	explicit MavlinkStreamGNSSIntegrity(Mavlink *mavlink) : MavlinkStream(mavlink) {}
+
+	uORB::Subscription _sensor_gps_sub{ORB_ID(sensor_gps), 0};
```
Comment (dagar) [inline src/modules/mavlink/streams/GNSS_INTEGRITY.hpp]: This actually needs to be the `vehicle_gps_position` topic (same sensor_gps_s struct) to respect the "primary" GPS if someone has more than 1 connected. 

```suggestion
	uORB::Subscription _vehicle_gps_position_sub{ORB_ID(vehicle_gps_position)};
```

**Comment by Tory9** [comment]
@dagar, hi. I have applied your suggestions and tested. let me know if I should adjust it more

File: boards/cubepilot/cubeorangeplus/default.px4board [hunk 16]
```diff
@@ -95,3 +95,4 @@ CONFIG_SYSTEMCMDS_UORB=y
 CONFIG_SYSTEMCMDS_USB_CONNECTED=y
 CONFIG_SYSTEMCMDS_VER=y
 CONFIG_SYSTEMCMDS_WORK_QUEUE=y
+CONFIG_MAVLINK_DIALECT="development"
```
Comment (dagar) [inline boards/cubepilot/cubeorangeplus/default.px4board]:
```suggestion
```

**Comment by Tory9** [comment]
hey @dagar, only MacOS build failed. is it ready for final review/ merge 🥺?

**Review by dagar — APPROVED** [review]

**Review by hamishwillee — APPROVED** [review]

**Comment by hamishwillee** [comment]
What's this waiting on now then @dagar - should we merge it?

**Comment by mrpollo** [comment]
Congrats @Tory9 @Louis-max-H

**Comment by hamishwillee** [comment]
> Congrats @Tory9 @Louis-max-H

And from me!

**Comment by Louis-max-H** [comment]
Yes, thanks everyone !
It has been a good first experience with open source development : )
