### ISSUE TITLE
[Bug] "brew install px4-sim-gazebo" generated 2 errors

### ISSUE THREAD

**Issue by ytl001** [PX4/PX4-Autopilot#24192]
### Describe the bug

Errors generated (see screenshot below) in "brew install px4-sim-gazebo" while following the steps in installing a new gazebo classic simulation on https://docs.px4.io/main/en/dev_setup/dev_env_mac.html.  This is the first time px4 has been installed on this computer.

MacOS Ventura 13.7.2
intel quadcore i5
16gb RAM

Command Line Tools were updated using "sudo xcode-select --install", even though it still complained that a newer version is available.

### Screenshot / Media
```
Yings-iMac:~ ytl$ brew install px4-sim-gazebo
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 3 taps (osrf/simulation, homebrew/core and homebrew/cask).
==> New Formulae
codesnap                                                           netatalk
==> New Casks
font-nanum-square         font-nanum-square-neo     font-nanum-square-round   macai                     serial-studio

You have 33 outdated formulae installed.

==> Fetching dependencies for px4/px4/px4-sim-gazebo: libpng, nettle, glib-networking, doxygen and osrf/simulation/gazebo11
==> Fetching libpng
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/manifests/1.6.45
############################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/blobs/sha256:0a59a94ee138a9903a2cf0f7a06b448d267647f245dec672ae56c92d27fd695
############################################################################################################################# 100.0%
==> Fetching nettle
==> Downloading https://ghcr.io/v2/homebrew/core/nettle/manifests/3.10.1
############################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/nettle/blobs/sha256:7d924af8b68729fbd75a279173b03da71219ee53c8c660198360dd4c8c0cde5
############################################################################################################################# 100.0%
==> Fetching glib-networking
==> Downloading https://ghcr.io/v2/homebrew/core/glib-networking/manifests/2.80.1
############################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/glib-networking/blobs/sha256:051b59d9c1a7d2403a8d34628d6c0acad7c25f50e9d25d4756095c
############################################################################################################################# 100.0%
==> Fetching doxygen
==> Downloading https://ghcr.io/v2/homebrew/core/doxygen/manifests/1.13.2
############################################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/doxygen/blobs/sha256:4dadc96efe27d3d615ae06a1196c444dd260201122a1b11612147615bd2fd0
############################################################################################################################# 100.0%
==> Fetching osrf/simulation/gazebo11
==> Downloading https://gist.githubusercontent.com/scpeters/9199370/raw/afe595587e38737c537124a3652db99de026c272/brew_python_fix.pat
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/12171d5787bf5709495604c1591fd598a9cffc3a055eb509bea588d33019cabc--brew_python_fix.patch
==> Downloading https://osrf-distributions.s3.amazonaws.com/gazebo/releases/gazebo-11.15.0.tar.bz2
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/e21841426e32b22934a46365b5def3c1390d536ea4c9fdfb4b1c008b593c3251--gazebo-11.15.0.tar.bz2
==> Fetching px4/px4/px4-sim-gazebo
==> Downloading https://raw.githubusercontent.com/PX4/PX4-Autopilot/master/Tools/px4.py
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/be4aff9b473b8b0c6bae0ff08a6611885de9d56ee3a477c05453bb6bbcaab246--px4.py
==> Installing px4-sim-gazebo from px4/px4
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.2.

==> Installing dependencies for px4/px4/px4-sim-gazebo: libpng, nettle, glib-networking, doxygen and osrf/simulation/gazebo11
==> Installing px4/px4/px4-sim-gazebo dependency: libpng
==> Downloading https://ghcr.io/v2/homebrew/core/libpng/manifests/1.6.45
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/45e044f04a9c9003b3fbe1ee536c125e6d68a8509f2d30cf7308fb6421d3b980--libpng-1.6.45.bottle_manifest.json
==> Pouring libpng--1.6.45.ventura.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.45: 28 files, 1.3MB
==> Installing px4/px4/px4-sim-gazebo dependency: nettle
==> Downloading https://ghcr.io/v2/homebrew/core/nettle/manifests/3.10.1
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/3a897a4b5866bef2225eb637641c992e5903a0748ec913a0747a253dcee0c4d8--nettle-3.10.1.bottle_manifest.json
==> Pouring nettle--3.10.1.ventura.bottle.tar.gz
🍺  /usr/local/Cellar/nettle/3.10.1: 96 files, 2.6MB
==> Installing px4/px4/px4-sim-gazebo dependency: glib-networking
==> Downloading https://ghcr.io/v2/homebrew/core/glib-networking/manifests/2.80.1
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/4f89b09c95b5e0b739677181793c68f87d7b371b8544cfd78f0b0be13534b4e5--glib-networking-2.80.1.bottle_manifest.json
==> Pouring glib-networking--2.80.1.ventura.bottle.tar.gz
==> /usr/local/opt/glib/bin/gio-querymodules /usr/local/lib/gio/modules
🍺  /usr/local/Cellar/glib-networking/2.80.1: 79 files, 755.2KB
==> Installing px4/px4/px4-sim-gazebo dependency: doxygen
==> Downloading https://ghcr.io/v2/homebrew/core/doxygen/manifests/1.13.2
Already downloaded: /Users/ytl/Library/Caches/Homebrew/downloads/e3ec488450cf70eadbfd85fcb869a3079fbada9546f9b39bdbffdee01fcb327b--doxygen-1.13.2.bottle_manifest.json
==> Pouring doxygen--1.13.2.ventura.bottle.tar.gz
🍺  /usr/local/Cellar/doxygen/1.13.2: 10 files, 22.7MB
==> Installing px4/px4/px4-sim-gazebo dependency: osrf/simulation/gazebo11
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.2.

==> Patching
==> Applying brew_python_fix.patch
==> cmake .. -DQWT_WIN_INCLUDE_DIR=/usr/local/opt/qwt-qt5/lib/qwt.framework/Headers -DQWT_WIN_LIBRARY_DIR=/usr/local/opt/qwt-qt5/lib
==> make install
Last 15 lines from /Users/ytl/Library/Logs/Homebrew/gazebo11/02.make:
/tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/gazebo/transport/Connection.hh:412:51: error: no type named 'iterator' in 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>'
                  boost::asio::ip::tcp::resolver::iterator _endPointIter);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/plugins/rest_web/RestUiWidget.cc:26:
In file included from /tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/plugins/rest_web/RestUiWidget.hh:27:
In file included from /tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/gazebo/gazebo.hh:20:
In file included from /tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/gazebo/gazebo_core.hh:21:
In file included from /tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/build/gazebo/transport/transport.hh:5:
/tmp/gazebo11-20250109-34994-vc8zyh/gazebo-11.15.0/gazebo/transport/IOManager.hh:45:28: error: no type named 'io_service' in namespace 'boost::asio'
      public: boost::asio::io_service &GetIO();
              ~~~~~~~~~~~~~^
2 errors generated.
make[2]: *** [plugins/rest_web/CMakeFiles/RestUiPlugin.dir/RestUiWidget.cc.o] Error 1
make[1]: *** [plugins/rest_web/CMakeFiles/RestUiPlugin.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/osrf/homebrew-simulation/issues

These open issues may also help:
gazebo11 fails to build on macos15.2 m1pro https://github.com/osrf/homebrew-simulation/issues/2927

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.2.

Yings-iMac:~ ytl$ 
```

### Vehicle type

None

**Comment by mrpollo** [comment]
Have you tried installing the Command Line Tools for Xcode?

**Comment by ytl001** [comment]
Yes, I followed the instructions to first remove the directory then install
xcode command line tools.  It didn't give any errors during installation.

**Comment by ytl001** [comment]
> ~Have you tried installing the Command Line Tools for Xcode?~ (sorry didn't ready)
> 
> Did you upgrade recently from from an intel to an m-based mac? this sometimes leads to issues with previous dependencies

No, I have been trying to install on the same intel based mac all along.
